// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIH-nN3G0s3-TZLT5R0Ny_JNNWEdgMwOg',
    appId: '1:807739844167:web:8f4b767639d3138fa0f362',
    messagingSenderId: '807739844167',
    projectId: 'testappbr01',
    authDomain: 'testappbr01.firebaseapp.com',
    storageBucket: 'testappbr01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrba58ngRg19WD6dtqkWd9Bbk6GWkmho',
    appId: '1:807739844167:android:9d626b06928db59ea0f362',
    messagingSenderId: '807739844167',
    projectId: 'testappbr01',
    storageBucket: 'testappbr01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGlUIPJQ0IHM7AAQnKSWKAer_PpkO9Zg',
    appId: '1:807739844167:ios:339c629e0c18396ea0f362',
    messagingSenderId: '807739844167',
    projectId: 'testappbr01',
    storageBucket: 'testappbr01.appspot.com',
    iosBundleId: 'com.example.test0925app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGlUIPJQ0IHM7AAQnKSWKAer_PpkO9Zg',
    appId: '1:807739844167:ios:c80373fbf65eedfea0f362',
    messagingSenderId: '807739844167',
    projectId: 'testappbr01',
    storageBucket: 'testappbr01.appspot.com',
    iosBundleId: 'com.example.test0925app.RunnerTests',
  );
}
